root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT10\_jet1\_mJ\",20,0.,400.,\"num\_primary\_vertices\",\"m\_\{J\}\ \(fat\ jet\ 1\)\ \[GeV\]\",\"NPV\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT15\_jet1\_mJ\",20,0.,400.,\"num\_primary\_vertices\",\"m\_\{J\}\ \(fat\ jet\ 1\)\ \[GeV\]\",\"NPV\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT20\_jet1\_mJ\",20,0.,400.,\"num\_primary\_vertices\",\"m\_\{J\}\ \(fat\ jet\ 1\)\ \[GeV\]\",\"NPV\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT25\_jet1\_mJ\",20,0.,400.,\"num\_primary\_vertices\",\"m\_\{J\}\ \(fat\ jet\ 1\)\ \[GeV\]\",\"NPV\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT30\_jet1\_mJ\",20,0.,400.,\"num\_primary\_vertices\",\"m\_\{J\}\ \(fat\ jet\ 1\)\ \[GeV\]\",\"NPV\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 

root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT10\_jet1\_nConst\",15,0.,15,\"num\_primary\_vertices\",\"n\_\{SJ\}\ \(fat\ jet\ 1\)\",\"NPV\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT15\_jet1\_nConst\",15,0.,15,\"num\_primary\_vertices\",\"n\_\{SJ\}\ \(fat\ jet\ 1\)\",\"NPV\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT20\_jet1\_nConst\",10,0.,10,\"num\_primary\_vertices\",\"n\_\{SJ\}\ \(fat\ jet\ 1\)\",\"NPV\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT25\_jet1\_nConst\",10,0.,10,\"num\_primary\_vertices\",\"n\_\{SJ\}\ \(fat\ jet\ 1\)\",\"NPV\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT30\_jet1\_nConst\",10,0.,10,\"num\_primary\_vertices\",\"n\_\{SJ\}\ \(fat\ jet\ 1\)\",\"NPV\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\)

root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT10\_jet2\_nConst\",15,0.,15,\"num\_primary\_vertices\",\"n\_\{SJ\}\ \(fat\ jet\ 2\)\",\"NPV\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT15\_jet2\_nConst\",15,0.,15,\"num\_primary\_vertices\",\"n\_\{SJ\}\ \(fat\ jet\ 2\)\",\"NPV\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT20\_jet2\_nConst\",10,0.,10,\"num\_primary\_vertices\",\"n\_\{SJ\}\ \(fat\ jet\ 2\)\",\"NPV\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT25\_jet2\_nConst\",10,0.,10,\"num\_primary\_vertices\",\"n\_\{SJ\}\ \(fat\ jet\ 2\)\",\"NPV\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT30\_jet2\_nConst\",10,0.,10,\"num\_primary\_vertices\",\"n\_\{SJ\}\ \(fat\ jet\ 2\)\",\"NPV\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\)

root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_jets\_pt20\",15,0.,15,\"num\_primary\_vertices\",\"n\_\{SJ\}\ \(p\_\{T\}\ \>\ 20\ GeV\)\",\"NPV\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_jets\_pt30\",15,0.,15,\"num\_primary\_vertices\",\"n\_\{SJ\}\ \(p\_\{T\}\ \>\ 30\ GeV\)\",\"NPV\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 

root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_fatpT10\_jets\",20,0.,20.,\"num\_primary\_vertices\",\"n\_\{J\}\ \(p\_\{T\}\ \>\ 50\ GeV\)\",\"NPV\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_fatpT15\_jets\",15,0.,15.,\"num\_primary\_vertices\",\"n\_\{J\}\ \(p\_\{T\}\ \>\ 50\ GeV\)\",\"NPV\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_fatpT20\_jets\",10,0.,10.,\"num\_primary\_vertices\",\"n\_\{J\}\ \(p\_\{T\}\ \>\ 50\ GeV\)\",\"NPV\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_fatpT25\_jets\",10,0.,10.,\"num\_primary\_vertices\",\"n\_\{J\}\ \(p\_\{T\}\ \>\ 50\ GeV\)\",\"NPV\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_fatpT30\_jets\",10,0.,10.,\"num\_primary\_vertices\",\"n\_\{J\}\ \(p\_\{T\}\ \>\ 50\ GeV\)\",\"NPV\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 

root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT10\_MJ\",30,0.,600.,\"num\_primary\_vertices\",\"M\_\{J\}\ \[GeV\]\",\"NPV\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT15\_MJ\",30,0.,600.,\"num\_primary\_vertices\",\"M\_\{J\}\ \[GeV\]\",\"NPV\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT20\_MJ\",30,0.,600.,\"num\_primary\_vertices\",\"M\_\{J\}\ \[GeV\]\",\"NPV\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT25\_MJ\",30,0.,600.,\"num\_primary\_vertices\",\"M\_\{J\}\ \[GeV\]\",\"NPV\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT30\_MJ\",30,0.,600.,\"num\_primary\_vertices\",\"M\_\{J\}\ \[GeV\]\",\"NPV\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 

root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT10\_jet1\_mJ\",20,0.,400.,\"num\_primary\_vertices\",\"m\_\{J\}\ \(fat\ jet\ 1\)\ \[GeV\]\",\"NPV\",\"reduced_trees\/TTJets*S14*.root\",\"ttbarhighPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT15\_jet1\_mJ\",20,0.,400.,\"num\_primary\_vertices\",\"m\_\{J\}\ \(fat\ jet\ 1\)\ \[GeV\]\",\"NPV\",\"reduced_trees\/TTJets*S14*.root\",\"ttbarhighPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT20\_jet1\_mJ\",20,0.,400.,\"num\_primary\_vertices\",\"m\_\{J\}\ \(fat\ jet\ 1\)\ \[GeV\]\",\"NPV\",\"reduced_trees\/TTJets*S14*.root\",\"ttbarhighPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT25\_jet1\_mJ\",20,0.,400.,\"num\_primary\_vertices\",\"m\_\{J\}\ \(fat\ jet\ 1\)\ \[GeV\]\",\"NPV\",\"reduced_trees\/TTJets*S14*.root\",\"ttbarhighPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT30\_jet1\_mJ\",20,0.,400.,\"num\_primary\_vertices\",\"m\_\{J\}\ \(fat\ jet\ 1\)\ \[GeV\]\",\"NPV\",\"reduced_trees\/TTJets*S14*.root\",\"ttbarhighPU\"\) 

root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_fatpT10\_jets\",20,0.,20.,\"num\_primary\_vertices\",\"n\_\{J\}\ \(p\_\{T\}\ \>\ 50\ GeV\)\",\"NPV\",\"reduced_trees\/TTJets*S14*.root\",\"ttbarhighPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_fatpT15\_jets\",15,0.,15.,\"num\_primary\_vertices\",\"n\_\{J\}\ \(p\_\{T\}\ \>\ 50\ GeV\)\",\"NPV\",\"reduced_trees\/TTJets*S14*.root\",\"ttbarhighPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_fatpT20\_jets\",10,0.,10.,\"num\_primary\_vertices\",\"n\_\{J\}\ \(p\_\{T\}\ \>\ 50\ GeV\)\",\"NPV\",\"reduced_trees\/TTJets*S14*.root\",\"ttbarhighPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_fatpT25\_jets\",10,0.,10.,\"num\_primary\_vertices\",\"n\_\{J\}\ \(p\_\{T\}\ \>\ 50\ GeV\)\",\"NPV\",\"reduced_trees\/TTJets*S14*.root\",\"ttbarhighPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_fatpT30\_jets\",10,0.,10.,\"num\_primary\_vertices\",\"n\_\{J\}\ \(p\_\{T\}\ \>\ 50\ GeV\)\",\"NPV\",\"reduced_trees\/TTJets*S14*.root\",\"ttbarhighPU\"\) 

root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT10\_MJ\",60,0.,1200.,\"num\_primary\_vertices\",\"M\_\{J\}\ \[GeV\]\",\"NPV\",\"reduced_trees\/TTJets*S14*.root\",\"ttbarhighPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT15\_MJ\",60,0.,1200.,\"num\_primary\_vertices\",\"M\_\{J\}\ \[GeV\]\",\"NPV\",\"reduced_trees\/TTJets*S14*.root\",\"ttbarhighPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT20\_MJ\",60,0.,1200.,\"num\_primary\_vertices\",\"M\_\{J\}\ \[GeV\]\",\"NPV\",\"reduced_trees\/TTJets*S14*.root\",\"ttbarhighPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT25\_MJ\",60,0.,1200.,\"num\_primary\_vertices\",\"M\_\{J\}\ \[GeV\]\",\"NPV\",\"reduced_trees\/TTJets*S14*.root\",\"ttbarhighPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT30\_MJ\",60,0.,1200.,\"num\_primary\_vertices\",\"M\_\{J\}\ \[GeV\]\",\"NPV\",\"reduced_trees\/TTJets*S14*.root\",\"ttbarhighPU\"\) 

root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT10\_jet1\_mJ\",20,0.,400.,\"num\_primary\_vertices\",\"m\_\{J\}\ \(fat\ jet\ 1\)\ \[GeV\]\",\"NPV\",\"reduced_trees\/TTJets*PU20*.root\",\"ttbarlowPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT15\_jet1\_mJ\",20,0.,400.,\"num\_primary\_vertices\",\"m\_\{J\}\ \(fat\ jet\ 1\)\ \[GeV\]\",\"NPV\",\"reduced_trees\/TTJets*PU20*.root\",\"ttbarlowPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT20\_jet1\_mJ\",20,0.,400.,\"num\_primary\_vertices\",\"m\_\{J\}\ \(fat\ jet\ 1\)\ \[GeV\]\",\"NPV\",\"reduced_trees\/TTJets*PU20*.root\",\"ttbarlowPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT25\_jet1\_mJ\",20,0.,400.,\"num\_primary\_vertices\",\"m\_\{J\}\ \(fat\ jet\ 1\)\ \[GeV\]\",\"NPV\",\"reduced_trees\/TTJets*PU20*.root\",\"ttbarlowPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT30\_jet1\_mJ\",20,0.,400.,\"num\_primary\_vertices\",\"m\_\{J\}\ \(fat\ jet\ 1\)\ \[GeV\]\",\"NPV\",\"reduced_trees\/TTJets*PU20*.root\",\"ttbarlowPU\"\) 

root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_fatpT10\_jets\",20,0.,20.,\"num\_primary\_vertices\",\"n\_\{J\}\ \(p\_\{T\}\ \>\ 50\ GeV\)\",\"NPV\",\"reduced_trees\/TTJets*PU20*.root\",\"ttbarlowPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_fatpT15\_jets\",15,0.,15.,\"num\_primary\_vertices\",\"n\_\{J\}\ \(p\_\{T\}\ \>\ 50\ GeV\)\",\"NPV\",\"reduced_trees\/TTJets*PU20*.root\",\"ttbarlowPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_fatpT20\_jets\",10,0.,10.,\"num\_primary\_vertices\",\"n\_\{J\}\ \(p\_\{T\}\ \>\ 50\ GeV\)\",\"NPV\",\"reduced_trees\/TTJets*PU20*.root\",\"ttbarlowPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_fatpT25\_jets\",10,0.,10.,\"num\_primary\_vertices\",\"n\_\{J\}\ \(p\_\{T\}\ \>\ 50\ GeV\)\",\"NPV\",\"reduced_trees\/TTJets*PU20*.root\",\"ttbarlowPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_fatpT30\_jets\",10,0.,10.,\"num\_primary\_vertices\",\"n\_\{J\}\ \(p\_\{T\}\ \>\ 50\ GeV\)\",\"NPV\",\"reduced_trees\/TTJets*PU20*.root\",\"ttbarlowPU\"\) 

root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT10\_MJ\",60,0.,1200.,\"num\_primary\_vertices\",\"M\_\{J\}\ \[GeV\]\",\"NPV\",\"reduced_trees\/TTJets*PU20*.root\",\"ttbarlowPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT15\_MJ\",60,0.,1200.,\"num\_primary\_vertices\",\"M\_\{J\}\ \[GeV\]\",\"NPV\",\"reduced_trees\/TTJets*PU20*.root\",\"ttbarlowPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT20\_MJ\",60,0.,1200.,\"num\_primary\_vertices\",\"M\_\{J\}\ \[GeV\]\",\"NPV\",\"reduced_trees\/TTJets*PU20*.root\",\"ttbarlowPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT25\_MJ\",60,0.,1200.,\"num\_primary\_vertices\",\"M\_\{J\}\ \[GeV\]\",\"NPV\",\"reduced_trees\/TTJets*PU20*.root\",\"ttbarlowPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT30\_MJ\",60,0.,1200.,\"num\_primary\_vertices\",\"M\_\{J\}\ \[GeV\]\",\"NPV\",\"reduced_trees\/TTJets*PU20*.root\",\"ttbarlowPU\"\) 


root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT10\_jet1\_mJ\",30,0.,1500.,\"num\_primary\_vertices\",\"m\_\{J\}\ \(fat\ jet\ 1\)\ \[GeV\]\",\"NPV\",\"reduced_trees\/SMS-T1tttt_2J_mGl-1500_mLSP-100*v75*.root\",\"T1tttt_1500_100\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT15\_jet1\_mJ\",30,0.,1500.,\"num\_primary\_vertices\",\"m\_\{J\}\ \(fat\ jet\ 1\)\ \[GeV\]\",\"NPV\",\"reduced_trees\/SMS-T1tttt_2J_mGl-1500_mLSP-100*v75*.root\",\"T1tttt_1500_100\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT20\_jet1\_mJ\",30,0.,1500.,\"num\_primary\_vertices\",\"m\_\{J\}\ \(fat\ jet\ 1\)\ \[GeV\]\",\"NPV\",\"reduced_trees\/SMS-T1tttt_2J_mGl-1500_mLSP-100*v75*.root\",\"T1tttt_1500_100\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT25\_jet1\_mJ\",30,0.,1500.,\"num\_primary\_vertices\",\"m\_\{J\}\ \(fat\ jet\ 1\)\ \[GeV\]\",\"NPV\",\"reduced_trees\/SMS-T1tttt_2J_mGl-1500_mLSP-100*v75*.root\",\"T1tttt_1500_100\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT30\_jet1\_mJ\",30,0.,1500.,\"num\_primary\_vertices\",\"m\_\{J\}\ \(fat\ jet\ 1\)\ \[GeV\]\",\"NPV\",\"reduced_trees\/SMS-T1tttt_2J_mGl-1500_mLSP-100*v75*.root\",\"T1tttt_1500_100\"\) 

root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_fatpT10\_jets\",20,0.,20.,\"num\_primary\_vertices\",\"n\_\{J\}\ \(p\_\{T\}\ \>\ 50\ GeV\)\",\"NPV\",\"reduced_trees\/SMS-T1tttt_2J_mGl-1500_mLSP-100*v75*.root\",\"T1tttt_1500_100\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_fatpT15\_jets\",15,0.,15.,\"num\_primary\_vertices\",\"n\_\{J\}\ \(p\_\{T\}\ \>\ 50\ GeV\)\",\"NPV\",\"reduced_trees\/SMS-T1tttt_2J_mGl-1500_mLSP-100*v75*.root\",\"T1tttt_1500_100\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_fatpT20\_jets\",10,0.,10.,\"num\_primary\_vertices\",\"n\_\{J\}\ \(p\_\{T\}\ \>\ 50\ GeV\)\",\"NPV\",\"reduced_trees\/SMS-T1tttt_2J_mGl-1500_mLSP-100*v75*.root\",\"T1tttt_1500_100\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_fatpT25\_jets\",10,0.,10.,\"num\_primary\_vertices\",\"n\_\{J\}\ \(p\_\{T\}\ \>\ 50\ GeV\)\",\"NPV\",\"reduced_trees\/SMS-T1tttt_2J_mGl-1500_mLSP-100*v75*.root\",\"T1tttt_1500_100\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_fatpT30\_jets\",10,0.,10.,\"num\_primary\_vertices\",\"n\_\{J\}\ \(p\_\{T\}\ \>\ 50\ GeV\)\",\"NPV\",\"reduced_trees\/SMS-T1tttt_2J_mGl-1500_mLSP-100*v75*.root\",\"T1tttt_1500_100\"\) 

root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT10\_MJ\",30,0.,1600.,\"num\_primary\_vertices\",\"M\_\{J\}\ \[GeV\]\",\"NPV\",\"reduced_trees\/SMS-T1tttt_2J_mGl-1500_mLSP-100*v75*.root\",\"T1tttt_1500_100\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT15\_MJ\",30,0.,1600.,\"num\_primary\_vertices\",\"M\_\{J\}\ \[GeV\]\",\"NPV\",\"reduced_trees\/SMS-T1tttt_2J_mGl-1500_mLSP-100*v75*.root\",\"T1tttt_1500_100\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT20\_MJ\",30,0.,1600.,\"num\_primary\_vertices\",\"M\_\{J\}\ \[GeV\]\",\"NPV\",\"reduced_trees\/SMS-T1tttt_2J_mGl-1500_mLSP-100*v75*.root\",\"T1tttt_1500_100\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT25\_MJ\",30,0.,1600.,\"num\_primary\_vertices\",\"M\_\{J\}\ \[GeV\]\",\"NPV\",\"reduced_trees\/SMS-T1tttt_2J_mGl-1500_mLSP-100*v75*.root\",\"T1tttt_1500_100\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT30\_MJ\",30,0.,1600.,\"num\_primary\_vertices\",\"M\_\{J\}\ \[GeV\]\",\"NPV\",\"reduced_trees\/SMS-T1tttt_2J_mGl-1500_mLSP-100*v75*.root\",\"T1tttt_1500_100\"\) 


## OOT PU!
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT10\_jet1\_mJ\",20,0.,400.,\"oot\_pu\",\"m\_\{J\}\ \(fat\ jet\ 1\)\ \[GeV\]\",\"OOTI\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT15\_jet1\_mJ\",20,0.,400.,\"oot\_pu\",\"m\_\{J\}\ \(fat\ jet\ 1\)\ \[GeV\]\",\"OOTI\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT20\_jet1\_mJ\",20,0.,400.,\"oot\_pu\",\"m\_\{J\}\ \(fat\ jet\ 1\)\ \[GeV\]\",\"OOTI\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT25\_jet1\_mJ\",20,0.,400.,\"oot\_pu\",\"m\_\{J\}\ \(fat\ jet\ 1\)\ \[GeV\]\",\"OOTI\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT30\_jet1\_mJ\",20,0.,400.,\"oot\_pu\",\"m\_\{J\}\ \(fat\ jet\ 1\)\ \[GeV\]\",\"OOTI\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 

root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT10\_jet1\_nConst\",15,0.,15,\"oot\_pu\",\"n\_\{SJ\}\ \(fat\ jet\ 1\)\",\"OOTI\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT15\_jet1\_nConst\",15,0.,15,\"oot\_pu\",\"n\_\{SJ\}\ \(fat\ jet\ 1\)\",\"OOTI\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT20\_jet1\_nConst\",10,0.,10,\"oot\_pu\",\"n\_\{SJ\}\ \(fat\ jet\ 1\)\",\"OOTI\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT25\_jet1\_nConst\",10,0.,10,\"oot\_pu\",\"n\_\{SJ\}\ \(fat\ jet\ 1\)\",\"OOTI\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT30\_jet1\_nConst\",10,0.,10,\"oot\_pu\",\"n\_\{SJ\}\ \(fat\ jet\ 1\)\",\"OOTI\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\)

root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_fatpT10\_jets\",20,0.,20.,\"oot\_pu\",\"n\_\{J\}\ \(p\_\{T\}\ \>\ 50\ GeV\)\",\"OOTI\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_fatpT15\_jets\",15,0.,15.,\"oot\_pu\",\"n\_\{J\}\ \(p\_\{T\}\ \>\ 50\ GeV\)\",\"OOTI\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_fatpT20\_jets\",10,0.,10.,\"oot\_pu\",\"n\_\{J\}\ \(p\_\{T\}\ \>\ 50\ GeV\)\",\"OOTI\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_fatpT25\_jets\",10,0.,10.,\"oot\_pu\",\"n\_\{J\}\ \(p\_\{T\}\ \>\ 50\ GeV\)\",\"OOTI\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_fatpT30\_jets\",10,0.,10.,\"oot\_pu\",\"n\_\{J\}\ \(p\_\{T\}\ \>\ 50\ GeV\)\",\"OOTI\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 

root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT10\_MJ\",30,0.,600.,\"oot\_pu\",\"M\_\{J\}\ \[GeV\]\",\"OOTI\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT15\_MJ\",30,0.,600.,\"oot\_pu\",\"M\_\{J\}\ \[GeV\]\",\"OOTI\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT20\_MJ\",30,0.,600.,\"oot\_pu\",\"M\_\{J\}\ \[GeV\]\",\"OOTI\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT25\_MJ\",30,0.,600.,\"oot\_pu\",\"M\_\{J\}\ \[GeV\]\",\"OOTI\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT30\_MJ\",30,0.,600.,\"oot\_pu\",\"M\_\{J\}\ \[GeV\]\",\"OOTI\",\"reduced_trees\/QCD_Pt*v75*.root\",\"qcd\"\) 

root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT10\_jet1\_mJ\",20,0.,400.,\"oot\_pu\",\"m\_\{J\}\ \(fat\ jet\ 1\)\ \[GeV\]\",\"OOTI\",\"reduced_trees\/TTJets*S14*.root\",\"ttbarhighPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT15\_jet1\_mJ\",20,0.,400.,\"oot\_pu\",\"m\_\{J\}\ \(fat\ jet\ 1\)\ \[GeV\]\",\"OOTI\",\"reduced_trees\/TTJets*S14*.root\",\"ttbarhighPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT20\_jet1\_mJ\",20,0.,400.,\"oot\_pu\",\"m\_\{J\}\ \(fat\ jet\ 1\)\ \[GeV\]\",\"OOTI\",\"reduced_trees\/TTJets*S14*.root\",\"ttbarhighPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT25\_jet1\_mJ\",20,0.,400.,\"oot\_pu\",\"m\_\{J\}\ \(fat\ jet\ 1\)\ \[GeV\]\",\"OOTI\",\"reduced_trees\/TTJets*S14*.root\",\"ttbarhighPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT30\_jet1\_mJ\",20,0.,400.,\"oot\_pu\",\"m\_\{J\}\ \(fat\ jet\ 1\)\ \[GeV\]\",\"OOTI\",\"reduced_trees\/TTJets*S14*.root\",\"ttbarhighPU\"\) 

root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_fatpT10\_jets\",20,0.,20.,\"oot\_pu\",\"n\_\{J\}\ \(p\_\{T\}\ \>\ 50\ GeV\)\",\"OOTI\",\"reduced_trees\/TTJets*S14*.root\",\"ttbarhighPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_fatpT15\_jets\",15,0.,15.,\"oot\_pu\",\"n\_\{J\}\ \(p\_\{T\}\ \>\ 50\ GeV\)\",\"OOTI\",\"reduced_trees\/TTJets*S14*.root\",\"ttbarhighPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_fatpT20\_jets\",10,0.,10.,\"oot\_pu\",\"n\_\{J\}\ \(p\_\{T\}\ \>\ 50\ GeV\)\",\"OOTI\",\"reduced_trees\/TTJets*S14*.root\",\"ttbarhighPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_fatpT25\_jets\",10,0.,10.,\"oot\_pu\",\"n\_\{J\}\ \(p\_\{T\}\ \>\ 50\ GeV\)\",\"OOTI\",\"reduced_trees\/TTJets*S14*.root\",\"ttbarhighPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_fatpT30\_jets\",10,0.,10.,\"oot\_pu\",\"n\_\{J\}\ \(p\_\{T\}\ \>\ 50\ GeV\)\",\"OOTI\",\"reduced_trees\/TTJets*S14*.root\",\"ttbarhighPU\"\) 

root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT10\_MJ\",60,0.,1200.,\"oot\_pu\",\"M\_\{J\}\ \[GeV\]\",\"OOTI\",\"reduced_trees\/TTJets*S14*.root\",\"ttbarhighPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT15\_MJ\",60,0.,1200.,\"oot\_pu\",\"M\_\{J\}\ \[GeV\]\",\"OOTI\",\"reduced_trees\/TTJets*S14*.root\",\"ttbarhighPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT20\_MJ\",60,0.,1200.,\"oot\_pu\",\"M\_\{J\}\ \[GeV\]\",\"OOTI\",\"reduced_trees\/TTJets*S14*.root\",\"ttbarhighPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT25\_MJ\",60,0.,1200.,\"oot\_pu\",\"M\_\{J\}\ \[GeV\]\",\"OOTI\",\"reduced_trees\/TTJets*S14*.root\",\"ttbarhighPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT30\_MJ\",60,0.,1200.,\"oot\_pu\",\"M\_\{J\}\ \[GeV\]\",\"OOTI\",\"reduced_trees\/TTJets*S14*.root\",\"ttbarhighPU\"\) 

root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT10\_jet1\_mJ\",20,0.,400.,\"oot\_pu\",\"m\_\{J\}\ \(fat\ jet\ 1\)\ \[GeV\]\",\"OOTI\",\"reduced_trees\/TTJets*PU20*.root\",\"ttbarlowPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT15\_jet1\_mJ\",20,0.,400.,\"oot\_pu\",\"m\_\{J\}\ \(fat\ jet\ 1\)\ \[GeV\]\",\"OOTI\",\"reduced_trees\/TTJets*PU20*.root\",\"ttbarlowPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT20\_jet1\_mJ\",20,0.,400.,\"oot\_pu\",\"m\_\{J\}\ \(fat\ jet\ 1\)\ \[GeV\]\",\"OOTI\",\"reduced_trees\/TTJets*PU20*.root\",\"ttbarlowPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT25\_jet1\_mJ\",20,0.,400.,\"oot\_pu\",\"m\_\{J\}\ \(fat\ jet\ 1\)\ \[GeV\]\",\"OOTI\",\"reduced_trees\/TTJets*PU20*.root\",\"ttbarlowPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT30\_jet1\_mJ\",20,0.,400.,\"oot\_pu\",\"m\_\{J\}\ \(fat\ jet\ 1\)\ \[GeV\]\",\"OOTI\",\"reduced_trees\/TTJets*PU20*.root\",\"ttbarlowPU\"\) 

root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_fatpT10\_jets\",20,0.,20.,\"oot\_pu\",\"n\_\{J\}\ \(p\_\{T\}\ \>\ 50\ GeV\)\",\"OOTI\",\"reduced_trees\/TTJets*PU20*.root\",\"ttbarlowPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_fatpT15\_jets\",15,0.,15.,\"oot\_pu\",\"n\_\{J\}\ \(p\_\{T\}\ \>\ 50\ GeV\)\",\"OOTI\",\"reduced_trees\/TTJets*PU20*.root\",\"ttbarlowPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_fatpT20\_jets\",10,0.,10.,\"oot\_pu\",\"n\_\{J\}\ \(p\_\{T\}\ \>\ 50\ GeV\)\",\"OOTI\",\"reduced_trees\/TTJets*PU20*.root\",\"ttbarlowPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_fatpT25\_jets\",10,0.,10.,\"oot\_pu\",\"n\_\{J\}\ \(p\_\{T\}\ \>\ 50\ GeV\)\",\"OOTI\",\"reduced_trees\/TTJets*PU20*.root\",\"ttbarlowPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_fatpT30\_jets\",10,0.,10.,\"oot\_pu\",\"n\_\{J\}\ \(p\_\{T\}\ \>\ 50\ GeV\)\",\"OOTI\",\"reduced_trees\/TTJets*PU20*.root\",\"ttbarlowPU\"\) 

root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT10\_MJ\",60,0.,1200.,\"oot\_pu\",\"M\_\{J\}\ \[GeV\]\",\"OOTI\",\"reduced_trees\/TTJets*PU20*.root\",\"ttbarlowPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT15\_MJ\",60,0.,1200.,\"oot\_pu\",\"M\_\{J\}\ \[GeV\]\",\"OOTI\",\"reduced_trees\/TTJets*PU20*.root\",\"ttbarlowPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT20\_MJ\",60,0.,1200.,\"oot\_pu\",\"M\_\{J\}\ \[GeV\]\",\"OOTI\",\"reduced_trees\/TTJets*PU20*.root\",\"ttbarlowPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT25\_MJ\",60,0.,1200.,\"oot\_pu\",\"M\_\{J\}\ \[GeV\]\",\"OOTI\",\"reduced_trees\/TTJets*PU20*.root\",\"ttbarlowPU\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT30\_MJ\",60,0.,1200.,\"oot\_pu\",\"M\_\{J\}\ \[GeV\]\",\"OOTI\",\"reduced_trees\/TTJets*PU20*.root\",\"ttbarlowPU\"\) 


root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT10\_jet1\_mJ\",30,0.,1500.,\"oot\_pu\",\"m\_\{J\}\ \(fat\ jet\ 1\)\ \[GeV\]\",\"OOTI\",\"reduced_trees\/SMS-T1tttt_2J_mGl-1500_mLSP-100*v75*.root\",\"T1tttt_1500_100\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT15\_jet1\_mJ\",30,0.,1500.,\"oot\_pu\",\"m\_\{J\}\ \(fat\ jet\ 1\)\ \[GeV\]\",\"OOTI\",\"reduced_trees\/SMS-T1tttt_2J_mGl-1500_mLSP-100*v75*.root\",\"T1tttt_1500_100\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT20\_jet1\_mJ\",30,0.,1500.,\"oot\_pu\",\"m\_\{J\}\ \(fat\ jet\ 1\)\ \[GeV\]\",\"OOTI\",\"reduced_trees\/SMS-T1tttt_2J_mGl-1500_mLSP-100*v75*.root\",\"T1tttt_1500_100\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT25\_jet1\_mJ\",30,0.,1500.,\"oot\_pu\",\"m\_\{J\}\ \(fat\ jet\ 1\)\ \[GeV\]\",\"OOTI\",\"reduced_trees\/SMS-T1tttt_2J_mGl-1500_mLSP-100*v75*.root\",\"T1tttt_1500_100\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT30\_jet1\_mJ\",30,0.,1500.,\"oot\_pu\",\"m\_\{J\}\ \(fat\ jet\ 1\)\ \[GeV\]\",\"OOTI\",\"reduced_trees\/SMS-T1tttt_2J_mGl-1500_mLSP-100*v75*.root\",\"T1tttt_1500_100\"\) 

root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_fatpT10\_jets\",20,0.,20.,\"oot\_pu\",\"n\_\{J\}\ \(p\_\{T\}\ \>\ 50\ GeV\)\",\"OOTI\",\"reduced_trees\/SMS-T1tttt_2J_mGl-1500_mLSP-100*v75*.root\",\"T1tttt_1500_100\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_fatpT15\_jets\",15,0.,15.,\"oot\_pu\",\"n\_\{J\}\ \(p\_\{T\}\ \>\ 50\ GeV\)\",\"OOTI\",\"reduced_trees\/SMS-T1tttt_2J_mGl-1500_mLSP-100*v75*.root\",\"T1tttt_1500_100\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_fatpT20\_jets\",10,0.,10.,\"oot\_pu\",\"n\_\{J\}\ \(p\_\{T\}\ \>\ 50\ GeV\)\",\"OOTI\",\"reduced_trees\/SMS-T1tttt_2J_mGl-1500_mLSP-100*v75*.root\",\"T1tttt_1500_100\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_fatpT25\_jets\",10,0.,10.,\"oot\_pu\",\"n\_\{J\}\ \(p\_\{T\}\ \>\ 50\ GeV\)\",\"OOTI\",\"reduced_trees\/SMS-T1tttt_2J_mGl-1500_mLSP-100*v75*.root\",\"T1tttt_1500_100\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"num\_fatpT30\_jets\",10,0.,10.,\"oot\_pu\",\"n\_\{J\}\ \(p\_\{T\}\ \>\ 50\ GeV\)\",\"OOTI\",\"reduced_trees\/SMS-T1tttt_2J_mGl-1500_mLSP-100*v75*.root\",\"T1tttt_1500_100\"\) 

root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT10\_MJ\",30,0.,1600.,\"oot\_pu\",\"M\_\{J\}\ \[GeV\]\",\"OOTI\",\"reduced_trees\/SMS-T1tttt_2J_mGl-1500_mLSP-100*v75*.root\",\"T1tttt_1500_100\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT15\_MJ\",30,0.,1600.,\"oot\_pu\",\"M\_\{J\}\ \[GeV\]\",\"OOTI\",\"reduced_trees\/SMS-T1tttt_2J_mGl-1500_mLSP-100*v75*.root\",\"T1tttt_1500_100\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT20\_MJ\",30,0.,1600.,\"oot\_pu\",\"M\_\{J\}\ \[GeV\]\",\"OOTI\",\"reduced_trees\/SMS-T1tttt_2J_mGl-1500_mLSP-100*v75*.root\",\"T1tttt_1500_100\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT25\_MJ\",30,0.,1600.,\"oot\_pu\",\"M\_\{J\}\ \[GeV\]\",\"OOTI\",\"reduced_trees\/SMS-T1tttt_2J_mGl-1500_mLSP-100*v75*.root\",\"T1tttt_1500_100\"\) 
root -b -q macros/MJ/plotXBinsOfY.C+\(\"fatpT30\_MJ\",30,0.,1600.,\"oot\_pu\",\"M\_\{J\}\ \[GeV\]\",\"OOTI\",\"reduced_trees\/SMS-T1tttt_2J_mGl-1500_mLSP-100*v75*.root\",\"T1tttt_1500_100\"\) 

