JobSubmit.csh ./scripts/skim_arne_tree.exe -i TreeMaker/mc/QCD_HT_1000ToInf_13TeV-madgraph_v1/
JobSubmit.csh ./scripts/skim_arne_tree.exe -i TreeMaker/mc/QCD_HT_1000ToInf_13TeV-madgraph_v1_ext1/
JobSubmit.csh ./scripts/skim_arne_tree.exe -i TreeMaker/mc/QCD_HT_250To500_13TeV-madgraph_v1/
JobSubmit.csh ./scripts/skim_arne_tree.exe -i TreeMaker/mc/QCD_HT_250To500_13TeV-madgraph_v1_ext1/
JobSubmit.csh ./scripts/skim_arne_tree.exe -i TreeMaker/mc/QCD_HT-500To1000_13TeV-madgraph_v1/
JobSubmit.csh ./scripts/skim_arne_tree.exe -i TreeMaker/mc/QCD_HT-500To1000_13TeV-madgraph_v1_ext1/
JobSubmit.csh ./scripts/skim_arne_tree.exe -i TreeMaker/mc/TBarToLeptons_s-channel-CSA14_Tune4C_13TeV-aMCatNLO-tauola/
JobSubmit.csh ./scripts/skim_arne_tree.exe -i TreeMaker/mc/TBarToLeptons_t-channel_Tune4C_CSA14_13TeV-aMCatNLO-tauola/
JobSubmit.csh ./scripts/skim_arne_tree.exe -i TreeMaker/mc/TTJets_MSDecaysCKM_central_Tune4C_13TeV-madgraph-tauola/
JobSubmit.csh ./scripts/skim_arne_tree.exe -i TreeMaker/mc/TToLeptons_s-channel-CSA14_Tune4C_13TeV-aMCatNLO-tauola/
JobSubmit.csh ./scripts/skim_arne_tree.exe -i TreeMaker/mc/TToLeptons_t-channel-CSA14_Tune4C_13TeV-aMCatNLO-tauola/
JobSubmit.csh ./scripts/skim_arne_tree.exe -i TreeMaker/mc/WJetsToLNu_HT-200to400/
JobSubmit.csh ./scripts/skim_arne_tree.exe -i TreeMaker/mc/WJetsToLNu_HT-400to600/
JobSubmit.csh ./scripts/skim_arne_tree.exe -i TreeMaker/mc/WJetsToLNu_HT-600toInf/
JobSubmit.csh ./scripts/skim_arne_tree.exe -i TreeMaker/mc/ZJetsToNuNu_HT-200to400/
JobSubmit.csh ./scripts/skim_arne_tree.exe -i TreeMaker/mc/ZJetsToNuNu_HT-400to600/
JobSubmit.csh ./scripts/skim_arne_tree.exe -i TreeMaker/mc/ZJetsToNuNu_HT-600toInf/
